import os
import logging

# Configurazioni e costanti
SOLUTIONS = ["biblioteca", "notte di novembre", "corda", "relazione passata", "benedetta farkas"]
VALID_ICONS = ["🕵️", "👮", "🧑‍🔬", "🔍", "🕵️‍♀️", "🚔", "🔬", "🧲", "📝", "🗝️", "🔎", "👀", "🧠", "🛡️", "📚", "🕰️"]
SECRET_KEY = os.environ.get("SECRET_KEY", "password-super-segreta-del-progetto-giallo")
DEBUG = os.environ.get("FLASK_DEBUG", "0").strip().lower() in {"1", "true", "yes", "on"}
HOST = os.environ.get("HOST", "0.0.0.0")
PORT = int(os.environ.get("PORT", "80"))
SOCKETIO_ALLOWED_ORIGINS = os.environ.get("SOCKETIO_ALLOWED_ORIGINS", "*")
RATE_LIMIT_WINDOW_SECONDS = int(os.environ.get("RATE_LIMIT_WINDOW_SECONDS", "10"))
RATE_LIMIT_MAX_REQUESTS = int(os.environ.get("RATE_LIMIT_MAX_REQUESTS", "12"))
ADMIN_URL_PATH = os.environ.get("ADMIN_URL_PATH", "admin-access")
ADMIN_PASSWORD_SHA256 = os.environ.get(
	"ADMIN_PASSWORD_SHA256",
	"c9e3f03ba57fc9e910567964387d648cf1d97f129219c24580c5adc33331e6e4"
)

STORY_TEXT = """Era una notte di novembre gelida e immobile quando il tranquillo silenzio che avvolgeva la villa Whitmore, una grande residenza londinese isolata dalla città, fu squarciato dalla scoperta di un omicidio. Quella sera la villa, antica e imponente qual era, aveva ospitato una festa elegante che prometteva allegria ma che si sarebbe presto trasformata in un incubo.

Ed era proprio Lord Percival Blackwell, uno degli uomini più rispettati di Londra, che fu trovato morto nella grande biblioteca della sua villa. Il suo corpo giaceva senza vita su una poltrona di velluto rosso con il volto pallido e contorto da un'espressione di terrore. Accanto a lui, una lettera incompleta giaceva su un tavolino; le parole confuse e il significato oscuro, come se avesse tentato di scrivere qualcosa di urgente ma fosse stato colto da un destino ineluttabile. La polizia arrivò in fretta ma la scena del crimine era già stata contaminata dalle voci e dalle paure degli ospiti di quella grande sera di festa. La villa era piena di sospetti e nessuno sembrava sapere nulla di certo, ma ciascun invitato avrebbe potuto nascondere qualcosa di più profondo. La lista si mostrava fitta e intricata, ma in particolare cinque persone, tutte con alibi dubbi e segreti ben celati, restarono sotto l'occhio vigile degli investigatori che avevano in pochi minuti riempito e perlustrato l'intero edificio.

Adelaide Moreau, una giovane e affascinante artista francese, aveva trascorso l’intera giornata presso la villa a parlare con Lord Blackwell delle sue ultime opere. La sua borsetta, nota a tutti come l’oggetto dal quale mai si allontana, era stata vista in prossimità del corpo poco prima che la signora ne rivendicasse la proprietà ma nessuno sapeva se fosse stato un caso. Ivan Rostov, un vecchio amico di università di Lord Blackwell, era giunto dalla fin Russia per partecipare all'evento. Sebbene il suo comportamento calmo e composto fosse apprezzato da molti, la sua natura irascibile era ben famigliare alla famiglia del Lord; infatti le discussioni passate di tema monetario con il padrone di casa lo avevano reso un inaffidabile sospetto. Richard Pierce, ricco imprenditore irlandese, aveva avuto frequenti divergenze con Lord Blackwell riguardo a un grosso affare; la sua nervosità quella sera era evidente: camminava avanti e indietro osservando con insistenza ogni angolo della villa, come se temesse di aver lasciato qualcosa che non deve assolutamente essere scoperto. Benedetta Farkas, una donna elegante di origini ungheresi, era conosciuta da tutti i presenti per aver avuto un passato sentimentale con Lord Blackwell, una relazione che non era mai stata del tutto chiara dagli inizi. Le sue emozioni erano sempre state intense e tempestose, e quella sera di certo non faceva eccezione. Infine Hugo Wells, un esperto di enigmi e misteri che spesso parlava di casi irrisolti, aveva attirato l'attenzione di molti per il suo atteggiamento distaccato dalle cordialità sociali e la sua insolita curiosità per lo straordinario giardino della villa che non aveva smesso di scrutare dalla biblioteca anche dopo l’arrivo della polizia.

La scena del crimine era tanto inquietante quanto le persone che vi si trovavano. Lord Blackwell era stato trovato nella sua amata biblioteca, un luogo silenzioso e appartato, dove l'odore dei libri antichi riempiva l'aria e forse ne copriva l’acidità per l’accaduto. Il suo corpo esanime giaceva accanto alla finestra dalla quale si scorgeva il giardino buio e deserto, quest’ultimo confinante con una boscaglia abbastanza intricata da potersi rivelare un’ottima via di fuga sotto gli occhi meno attenti secondo gli investigatori. Inoltre, non era da escludere la possibilità di usare la biblioteca come escamotage per distogliere l’attenzione su un possibile spostamento del corpo in un secondo momento; ciò apriva a molte più piste percorribili e il tempo per trovare possibili impronte o tracce nella villa sembrava stringere sempre più.

La polizia con il suo consueto rigore aveva iniziato a interrogare i presenti. Si è scoperto che il giardino, un luogo apparentemente tranquillo di notte, era stato percorso da alcuni degli invitati prima che il corpo venisse trovato. La sala da pranzo, il cuore della serata dove tutti avevano consumato il pasto, era un altro possibile luogo del delitto sebbene in un luogo così frequentato fosse estremamente difficile agire di nascosto. Il lungo e buio corridoio che collegava tutte le stanze di Villa Whitmore sembrava non offrire alcuna via di fuga certa, ma la servitù ha confermato di aver notato strani movimenti e rumori provenire da diverse porte.

E che dire dei diversi oggetti sospetti trovati nei dintorni e nella villa. Un coltello affilato è stata la prima arma trovata accanto al corpo, così vicina alla scena del delitto ma senza lasciare la minima traccia di sangue. Qualche interrogato parlò di una pistola che si diceva appartenesse a uno degli ospiti presenti più misteriosi; la presenza dell’arma alla serata non era certa perché pareva essere una leggenda diffusasi nei quartieri più poveri di Londra. Un’ulteriore oggetto misterioso che era stato notato era la corda spessa ritrovata nei pressi del giardino e nascosta tra i diversi arbusti colorati; nessuno riusciva a capire chi mai avesse potuto avere la forza di un tale atto quale lo strangolamento, di certo non una donna. Alcuni sospettavano anche che Lord Blackwell fosse stato avvelenato alla cena che lui stesso aveva organizzato, forse da una sostanza che avrebbe agito in silenzio e velocemente dal suo bicchiere di vino. Non passò inosservata ad uno dei giardinieri interrogati la scomparsa di una vanga dal suo ripostiglio, uno strumento abbastanza pesante che sarebbe potuto servire a qualcosa di ben diverso dal dissodare il terreno e proprio sul tramontare della giornata.

La villa Whitmore, con la sua bellezza inquietante, nascondeva più di quanto le sue stanze lussuose volessero far credere. Ogni angolo e ogni oggetto sembrava contenere indizi ma erano solo frammenti sparsi e confusi che la polizia stava cercando di mettere insieme. Lord Blackwell era morto e il suo assassino restava ancora invisibile, e la verità, come sempre accade nei casi più oscuri, si celava dietro maschere di sospetto, segreti e silenzi.
"""

CLASSROOM_LINK = "https://classroom.google.com/c/ODUxNzYyMzkyNjIx?cjc=kfolr33h"

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logging.info("Config module loaded")